### PR TITLE
Allow marshmallow version greater than 3

### PR DESCRIPTION
**Pull request by rambobinator**

### CODE REVIEW

**Comment by trubesv** [comment]
Thanks for this!

What about automatic RAISE on fields present in the payload but not specified in the schema?

See https://github.com/marshmallow-code/marshmallow/pull/838 for reference :)

**Comment by rambobinator** [comment]
@trubesv What do you mean ?
It will then raise a marshmallow validation exception, which is catched by this decorator.

**Comment by trubesv** [comment]
@rambobinator What I mean is that it is a potential breaking change for users of this Flask extension.

As of now, nothing is done when there are extra fields in the payload so the requests go through, but if you update to our next release containing the bump to Marshmallow >3, you will get 400s in those cases :)

**Comment by rambobinator** [comment]
That's right, @ramnes maybe we should stick marshmallow version to <3 in requirements ?

**Comment by rambobinator** [comment]
There is a compatible release operator that may be used here:
`marshmallow ~= 2.15.4`
Is it ok for you ?

**Comment by ramnes** [comment]
> As of now, nothing is done when there are extra fields in the payload so the requests go through, but if you update to our next release containing the bump to Marshmallow >3, you will get 400s in those cases :)

This is a non-issue because Flask-Stupe does not have any install requirement else than `Flask` (`requirements.txt` is just used for development). What this mean is that even if you update to our next release, that won't update Marshmallow by itself.

**Comment by trubesv** [comment]
Thanks for clarifying that!

LGTM then 🚀

**Pull request merged**
